// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Scattergories
{
    [Register("CategoriesCell")]
    public partial class CategoriesCell : UITableViewCell
	{
        UILabel titleLabel;
        public static readonly NSString Key = new NSString("CategoriesCell");

        public CategoriesCell (IntPtr handle) : base (handle)
		{
            titleLabel = new UILabel
            {
                Text = "",
                TextAlignment = UITextAlignment.Left,
                TranslatesAutoresizingMaskIntoConstraints = false
            };

            UIView separator = new UIView
            {
                TranslatesAutoresizingMaskIntoConstraints = false,
                BackgroundColor = UIColor.Black
            };

            this.ContentView.AddSubviews(separator, titleLabel);

            var metrics = new NSDictionary();
            var viewsToResize = NSDictionary.FromObjectsAndKeys(new object[] { titleLabel, separator }, new object[] { "titleLabel", "separator" });

            this.ContentView.AddConstraints(NSLayoutConstraint.FromVisualFormat(@"V:|[titleLabel(50)]|", 0, metrics, viewsToResize));
            this.ContentView.AddConstraints(NSLayoutConstraint.FromVisualFormat(@"H:|-(15)-[titleLabel]|", 0, metrics, viewsToResize));
            this.ContentView.AddConstraints(NSLayoutConstraint.FromVisualFormat(@"H:|[separator]|", 0, metrics, viewsToResize));
            this.ContentView.AddConstraints(NSLayoutConstraint.FromVisualFormat(@"V:[separator(1)]|", 0, metrics, viewsToResize));

        }
        public void LayoutCell(string text)
        {
            titleLabel.Text = text;
            titleLabel.TextColor = UIColor.Black;
        }
    }
}
