// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Scattergories
{
	public partial class Main_Split_Controller : UISplitViewController
	{
		public Main_Split_Controller (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var masterController = this.ViewControllers[0];
            var detailsController = this.ViewControllers[1];
            this.PreferredDisplayMode = UISplitViewControllerDisplayMode.AllVisible;


            ((Dashboard_Controller)masterController.ChildViewControllers[0]).OnNewGame += (sender, e) => {
                ((Categories_Controller)detailsController).InitNewGame();
            };

            ShowDetailViewController(Storyboard.InstantiateViewController("CategoriesController"), this);
        }
    }
}
